return {
  ["Any Housing"] = {
      _id = "Any Housing",
      _displayName = "Basic Housing",
      _description = "Most species require at least basic shelter from the constant rainfall and gusting winds.",
      _iconFilename = "Icon_Need_Shelter.png",
      _category = "Housing",
      _isAtHearth = false,
  },
  ["Bat Housing"] = {
      _id = "Bat Housing",
      _displayName = "Bat Housing",
      _description = "Bats prefer to live in spacious and dark homes. Bat Houses are required to fulfill this need.",
      _iconFilename = "Icon_Needs_BatHousing.png",
      _category = "Housing",
      _isAtHearth = false,
  },
  ["Beaver Housing"] = {
      _id = "Beaver Housing",
      _displayName = "Beaver Housing",
      _description = "Beavers prefer to live in cozy, wooden homes. Beaver Houses are required to fulfill this need.",
      _iconFilename = "Icon_Need_beaverHousing.png",
      _category = "Housing",
      _isAtHearth = false,
  },
  ["Fox Housing"] = {
      _id = "Fox Housing",
      _displayName = "Fox Housing",
      _description = "Foxes prefer to live in wooden, well camouflaged houses. Fox Houses are required to fulfill this need.",
      _iconFilename = "Icon_Need_FoxHousing.png",
      _category = "Housing",
      _isAtHearth = false,
  },
  ["Frog Housing"] = {
      _id = "Frog Housing",
      _displayName = "Frog Housing",
      _description = "Frogs are at home in water. Frog Houses are required to fulfill this need.",
      _iconFilename = "Icon_Need_FrogHousing 1.png",
      _category = "Housing",
      _isAtHearth = false,
  },
  ["Harpy Housing"] = {
      _id = "Harpy Housing",
      _displayName = "Harpy Housing",
      _description = "Harpies prefer to live in well-lit, spacious homes. Harpy Houses are required to fulfill this need.",
      _iconFilename = "Icon_Need_HarpyHousing.png",
      _category = "Housing",
      _isAtHearth = false,
  },
  ["Human Housing"] = {
      _id = "Human Housing",
      _displayName = "Human Housing",
      _description = "Humans prefer to live in solid, safe homes. Human Houses are required to fulfill this need.",
      _iconFilename = "Icon_Need_HumanHousing.png",
      _category = "Housing",
      _isAtHearth = false,
  },
  ["Lizard Housing"] = {
      _id = "Lizard Housing",
      _displayName = "Lizard Housing",
      _description = "Lizards prefer to live in warm, dry homes. Lizard Houses are required to fulfill this need.",
      _iconFilename = "Icon_Need_LizardHousing.png",
      _category = "Housing",
      _isAtHearth = false,
  },
  ["Jerky"] = {
      _id = "Jerky",
      _displayName = "Jerky",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[food processed] jerky\"> jerky. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Resource_Jerky.png",
      _category = "Complex Food",
      _isAtHearth = true,
  },
  ["Porridge"] = {
      _id = "Porridge",
      _displayName = "Porridge",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[food processed] porridge\"> porridge. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Resource_Porridge.png",
      _category = "Complex Food",
      _isAtHearth = true,
  },
  ["Paste"] = {
      _id = "Paste",
      _displayName = "Paste",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[food processed] paste\"> paste. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Resource_Paste 1.png",
      _category = "Complex Food",
      _isAtHearth = true,
  },
  ["Skewer"] = {
      _id = "Skewer",
      _displayName = "Skewers",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[food processed] skewers\"> skewers. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Resource_Skewers.png",
      _category = "Complex Food",
      _isAtHearth = true,
  },
  ["Biscuits"] = {
      _id = "Biscuits",
      _displayName = "Biscuits",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[food processed] biscuits\"> biscuits. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Resource_Biscuits.png",
      _category = "Complex Food",
      _isAtHearth = true,
  },
  ["Pie"] = {
      _id = "Pie",
      _displayName = "Pie",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[food processed] pie\"> pie. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Resource_Pie.png",
      _category = "Complex Food",
      _isAtHearth = true,
  },
  ["Pickled Goods"] = {
      _id = "Pickled Goods",
      _displayName = "Pickled Goods",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[food processed] pickled goods\"> pickled goods. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Resource_PickledGoods.png",
      _category = "Complex Food",
      _isAtHearth = true,
  },
  ["Boots"] = {
      _id = "Boots",
      _displayName = "Boots",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[needs] boots\"> boots. Satisfying this need grants a movement speed bonus.",
      _iconFilename = "Icon_Resource_Boots 1.png",
      _category = "Clothing",
      _isAtHearth = true,
  },
  ["Clothes"] = {
      _id = "Clothes",
      _displayName = "Coats",
      _description = "This need is fulfilled at the Hearth. It requires <sprite name=\"[needs] coats\"> coats. Satisfying this need grants a Resolve bonus during the storm.",
      _iconFilename = "Icon_Resource_Coats.png",
      _category = "Clothing",
      _isAtHearth = true,
  },
  ["Leisure"] = {
      _id = "Leisure",
      _displayName = "Leisure",
      _description = "This need is fulfilled in: Tavern, Monastery, Market. It requires <sprite name=\"[needs] ale\"> ale. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Need_Leisure.png",
      _category = "Services",
      _isAtHearth = false,
  },
  ["Brawling"] = {
      _id = "Brawling",
      _displayName = "Brawling",
      _description = "This need is fulfilled in: Clan Hall, Forum, Academy. Requires <sprite name=\"[needs] training gear\"> training gear. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Need_Brawling.png",
      _category = "Services",
      _isAtHearth = false,
  },
  ["Religion"] = {
      _id = "Religion",
      _displayName = "Religion",
      _description = "This need is fulfilled in: Temple, Monastery, Tea Doctor. It requires <sprite name=\"[needs] incense\"> incense. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Need_Religion.png",
      _category = "Services",
      _isAtHearth = false,
  },
  ["Education"] = {
      _id = "Education",
      _displayName = "Education",
      _description = "This need is fulfilled in: Temple, Holy Guild House, Guild House, Academy. It requires <sprite name=\"[needs] scrolls\"> scrolls. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Need_Education.png",
      _category = "Services",
      _isAtHearth = false,
  },
  ["Luxury"] = {
      _id = "Luxury",
      _displayName = "Luxury",
      _description = "This need is fulfilled in: Tavern, Holy Guild House, Forum, Guild House. It requires <sprite name=\"[needs] wine\"> wine. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Need_Luxury.png",
      _category = "Services",
      _isAtHearth = false,
  },
  ["Treatment"] = {
      _id = "Treatment",
      _displayName = "Treatment",
      _description = "This need is fulfilled in: Market, Tea Doctor, Bath House. It requires <sprite name=\"[needs] tea\"> tea. Satisfying this need increases the chance of producing double yields.",
      _iconFilename = "Icon_Need_Treatment.png",
      _category = "Services",
      _isAtHearth = false,
  },
}
