return {
    ["[Crafting] Coal"] = {
        _id = "[Crafting] Coal",
        _displayName = "Coal",
        _description = "Efficient fuel. \n \n <b>Obtained in:</b> Kiln, Mine, Brick Oven",
        _category = "Fuel & Exploration",
        _isEatable = false,
        _isBurnable = true,
        _burningTime = 40,
        _tradingSellValue = 3.5,
        _tradingBuyValue = 6,
        _iconFilename = "Icon_Resource_Coal.png",
    },
    ["[Crafting] Dye"] = {
        _id = "[Crafting] Dye",
        _displayName = "Dye",
        _description = "Used for crafting.\n \n <b>Produced in:</b> Tinctury, Apothecary, Manufactory, Cobbler",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.14,
        _tradingBuyValue = 1.9,
        _iconFilename = "Icon_Resource_Pigment.png",
    },
    ["[Crafting] Flour"] = {
        _id = "[Crafting] Flour",
        _displayName = "Flour",
        _description = "Used for cooking.\n \n <b>Produced in:</b> Rain Mill, Provisioner, Stamping Mill, Supplier, Press",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Flour.png",
    },
    ["[Crafting] Oil"] = {
        _id = "[Crafting] Oil",
        _displayName = "Oil",
        _description = "Efficient fuel. \n \n <b>Obtained in:</b> Press, Druid's Hut, Butcher",
        _category = "Fuel & Exploration",
        _isEatable = false,
        _isBurnable = true,
        _burningTime = 25,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Oil.png",
    },
    ["[Crafting] Salt"] = {
        _id = "[Crafting] Salt",
        _displayName = "Salt",
        _description = "A valuable and highly absorbent mineral.\n\n<b>Obtained in:</b> Mine",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_SaltNEW.png",
    },
    ["[Crafting] Sea Marrow"] = {
        _id = "[Crafting] Sea Marrow",
        _displayName = "Sea Marrow",
        _description = "Efficient fuel. \n \n <b>Obtained in:</b> Stonecutters' Camp",
        _category = "Fuel & Exploration",
        _isEatable = false,
        _isBurnable = true,
        _burningTime = 40,
        _tradingSellValue = 3.75,
        _tradingBuyValue = 6.25,
        _iconFilename = "Icon_Resource_SeaMarrow.png",
    },
    ["[Food Processed] Biscuits"] = {
        _id = "[Food Processed] Biscuits",
        _displayName = "Biscuits",
        _description = "Tasty and crunchy. Liked by: Humans, Beavers, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for biscuits have an increased chance of producing double yields.\n\n<b>Produced in:</b> Brick Oven, Bakery, Cookhouse, Cannery, Field Kitchen",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.3,
        _tradingBuyValue = 4.6,
        _iconFilename = "Icon_Resource_Biscuits.png",
    },
    ["[Food Processed] Jerky"] = {
        _id = "[Food Processed] Jerky",
        _displayName = "Jerky",
        _description = "Preserved, dried meat. Liked by: Lizards, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for jerky have an increased chance of producing double yields.\n\n<b>Produced in:</b> Smokehouse, Butcher, Apothecary, Kiln",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.7,
        _tradingBuyValue = 3.4,
        _iconFilename = "Icon_Resource_Jerky.png",
    },
    ["[Food Processed] Paste"] = {
        _id = "[Food Processed] Paste",
        _displayName = "Paste",
        _description = "A smooth paste, no chewing required. Liked by: <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for paste have an increased chance of producing double yields.\n\n<b>Produced in:</b> Cannery, Grill, Press, Rain Mill, Field Kitchen",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.75,
        _tradingBuyValue = 3.5,
        _iconFilename = "Icon_Resource_Paste 1.png",
    },
    ["[Food Processed] Pickled Goods"] = {
        _id = "[Food Processed] Pickled Goods",
        _displayName = "Pickled Goods",
        _description = "A Beaver specialty. Liked by: Beavers, Lizards, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for pickled goods have an increased chance of producing double yields.\n\n<b>Produced in:</b> Cellar, Granary, Distillery, Beanery, Field Kitchen",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2,
        _tradingBuyValue = 4,
        _iconFilename = "Icon_Resource_PickledGoods.png",
    },
    ["[Food Processed] Pie"] = {
        _id = "[Food Processed] Pie",
        _displayName = "Pie",
        _description = "A savory delicacy. Liked by: Humans, Lizards, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for pie have an increased chance of producing double yields.\n\n<b>Produced in:</b> Bakery, Pantry, Furnace, Smelter",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.1,
        _tradingBuyValue = 4.2,
        _iconFilename = "Icon_Resource_Pie.png",
    },
    ["[Food Processed] Porridge"] = {
        _id = "[Food Processed] Porridge",
        _displayName = "Porridge",
        _description = "A nutritious and warming meal. Liked by: Humans, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for porridge have an increased chance of producing double yields.\n\n<b>Produced in:</b> Beanery, Cookhouse, Pantry, Brewery",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.9,
        _tradingBuyValue = 3.8,
        _iconFilename = "Icon_Resource_Porridge.png",
    },
    ["[Food Processed] Skewers"] = {
        _id = "[Food Processed] Skewers",
        _displayName = "Skewers",
        _description = "A Lizard specialty. Liked by: Lizards, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for skewers have an increased chance of producing double yields.\n\n<b>Produced in:</b> Grill, Cookhouse, Butcher, Furnace, Field Kitchen",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2,
        _tradingBuyValue = 4,
        _iconFilename = "Icon_Resource_Skewers.png",
    },
    ["[Food Raw] Berries"] = {
        _id = "[Food Raw] Berries",
        _displayName = "Berries",
        _description = "Common food source.\n \n <b>Obtained in:</b> Plantation, Herbalists' Camp, Small Herbalists' Camp",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Berries.png",
    },
    ["[Food Raw] Eggs"] = {
        _id = "[Food Raw] Eggs",
        _displayName = "Eggs",
        _description = "Common food source.\n \n <b>Obtained in:</b> Trappers' Camp, Ranch, Small Trappers' Camp",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Eggs.png",
    },
    ["[Food Raw] Fish"] = {
        _id = "[Food Raw] Fish",
        _displayName = "Fish",
        _description = "Plenty of them in the sea. A common food source.\n\n<b>Obtained at:</b> Fishing Hut, Small Fishing Hut",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Fish 1.png",
    },
    ["[Food Raw] Grain"] = {
        _id = "[Food Raw] Grain",
        _displayName = "Grain",
        _description = "Isn't eaten raw, but can be processed.\n \n <b>Obtained in:</b> Homestead, Small Farm, Foragers' Camp, Small Foragers' Camp",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Grain.png",
    },
    ["[Food Raw] Herbs"] = {
        _id = "[Food Raw] Herbs",
        _displayName = "Herbs",
        _description = "Isn't eaten raw, but can be processed.\n \n <b>Obtained in:</b> Herb Garden, Greenhouse, Herbalists' Camp, Small Herbalists' Camp",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Herbs.png",
    },
    ["[Food Raw] Insects"] = {
        _id = "[Food Raw] Insects",
        _displayName = "Insects",
        _description = "Common food source.\n \n <b>Obtained in:</b> Trappers' Camp, Small Trappers' Camp",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Insects.png",
    },
    ["[Food Raw] Meat"] = {
        _id = "[Food Raw] Meat",
        _displayName = "Meat",
        _description = "Common food source.\n \n <b>Obtained in:</b> Trappers' Camp, Ranch, Small Trappers' Camp",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Meat.png",
    },
    ["[Food Raw] Mushrooms"] = {
        _id = "[Food Raw] Mushrooms",
        _displayName = "Mushrooms",
        _description = "Common food source.\n \n <b>Obtained in:</b> Greenhouse, Herbalists' Camp, Homestead, Small Herbalists' Camp",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Mushrooms.png",
    },
    ["[Food Raw] Roots"] = {
        _id = "[Food Raw] Roots",
        _displayName = "Roots",
        _description = "Common food source.\n \n <b>Obtained in:</b> Foragers' Camp, Herb Garden, Small Foragers' Camp",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Roots.png",
    },
    ["[Food Raw] Vegetables"] = {
        _id = "[Food Raw] Vegetables",
        _displayName = "Vegetables",
        _description = "Common food source.\n \n <b>Obtained in:</b> Foragers' Camp, Homestead, Small Farm, Small Foragers' Camp",
        _category = "Food",
        _isEatable = true,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 4.5,
        _iconFilename = "Icon_Resource_Vegetables.png",
    },
    ["[Mat Processed] Bricks"] = {
        _id = "[Mat Processed] Bricks",
        _displayName = "Bricks",
        _description = "Mostly used for construction.\n \n <b>Produced in:</b> Brickyard, Workshop, Stamping Mill, Kiln, Crude Workstation",
        _category = "Building Materials",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 3.3,
        _tradingBuyValue = 5.5,
        _iconFilename = "Icon_Resource_Bricks.png",
    },
    ["[Mat Processed] Fabric"] = {
        _id = "[Mat Processed] Fabric",
        _displayName = "Fabric",
        _description = "Used for construction or production of clothes.\n \n <b>Produced in:</b> Weaver, Workshop, Granary, Manufactory, Crude Workstation",
        _category = "Building Materials",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 3.3,
        _tradingBuyValue = 5.5,
        _iconFilename = "Icon_Resource_Fabric.png",
    },
    ["[Mat Processed] Parts"] = {
        _id = "[Mat Processed] Parts",
        _displayName = "Parts",
        _description = "Rare items used for construction. Difficult to produce in this harsh environment.",
        _category = "Building Materials",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 28.8,
        _tradingBuyValue = 48,
        _iconFilename = "Icon_Resource_Parts.png",
    },
    ["[Mat Processed] Pipe"] = {
        _id = "[Mat Processed] Pipe",
        _displayName = "Pipes",
        _description = "Used to install Rainpunk Engines in production buildings and build Geyser Pumps.\n \n <b>Produced in:</b> Smithy, Toolshop, Crude Workstation, Workshop",
        _category = "Building Materials",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 7,
        _tradingBuyValue = 12,
        _iconFilename = "Icon_Resource_Pipes.png",
    },
    ["[Mat Processed] Planks"] = {
        _id = "[Mat Processed] Planks",
        _displayName = "Planks",
        _description = "Mostly used for construction.\n \n <b>Produced in:</b> Lumber Mill, Workshop, Carpenter, Supplier, Crude Workstation",
        _category = "Building Materials",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.1,
        _tradingBuyValue = 3.5,
        _iconFilename = "Icon_Resource_Planks.png",
    },
    ["[Mat Raw] Algae"] = {
        _id = "[Mat Raw] Algae",
        _displayName = "Algae",
        _description = "Slimy, tough fibers fished from murky waters. Used for crafting.\n\n<b>Obtained at:</b> Fishing Hut, Small Fishing Hut",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Algae 1.png",
    },
    ["[Mat Raw] Clay"] = {
        _id = "[Mat Raw] Clay",
        _displayName = "Clay",
        _description = "Flesh of the earth. Used mostly for crafting.\n \n <b>Obtained in:</b> Stonecutters' Camp, Clay Pit",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Clay.png",
    },
    ["[Mat Raw] Leather"] = {
        _id = "[Mat Raw] Leather",
        _displayName = "Leather",
        _description = "Used for crafting.\n \n <b>Obtained in:</b> Harvesters' Camp, Ranch",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Leather.png",
    },
    ["[Mat Raw] Plant Fibre"] = {
        _id = "[Mat Raw] Plant Fibre",
        _displayName = "Plant Fiber",
        _description = "Used for crafting.\n \n <b>Obtained in:</b> Homestead, Plantation, Harvesters' Camp",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_PlantFiber.png",
    },
    ["[Mat Raw] Reeds"] = {
        _id = "[Mat Raw] Reeds",
        _displayName = "Reed",
        _description = "Used for crafting.\n \n <b>Obtained in:</b> Harvesters' Camp, Clay Pit",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Reeds.png",
    },
    ["[Mat Raw] Resin"] = {
        _id = "[Mat Raw] Resin",
        _displayName = "Resin",
        _description = "Used for crafting.\n \n <b>Obtained in:</b> Forester's Hut, Clay Pit",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Resin.png",
    },
    ["[Mat Raw] Scales"] = {
        _id = "[Mat Raw] Scales",
        _displayName = "Scales",
        _description = "Durable fish skin, richly infused with copper. Used for crafting.\n\n<b>Obtained at:</b> Fishing Hut, Small Fishing Hut",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Scales 1.png",
    },
    ["[Mat Raw] Sparkdew"] = {
        _id = "[Mat Raw] Sparkdew",
        _displayName = "Sparkdew",
        _description = "Charged rainwater. Extremely useful, and dangerous at the same time. Obtained by: ",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 0.75,
        _tradingBuyValue = 1.25,
        _iconFilename = "Icon_Resource_Sparkdew.png",
    },
    ["[Mat Raw] Stone"] = {
        _id = "[Mat Raw] Stone",
        _displayName = "Stone",
        _description = "Bones of the earth. Used mostly for crafting.\n \n <b>Obtained in:</b> Stonecutters' Camp",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Stone.png",
    },
    ["[Mat Raw] Wood"] = {
        _id = "[Mat Raw] Wood",
        _displayName = "Wood",
        _description = "An abundant, yet crucial resource. \n \n <b>Obtained in:</b> Woodcutters' Camp",
        _category = "Fuel & Exploration",
        _isEatable = false,
        _isBurnable = true,
        _burningTime = 12,
        _tradingSellValue = 0.75,
        _tradingBuyValue = 1.25,
        _iconFilename = "Icon_Resource_Wood.png",
    },
    ["[Metal] Copper Bar"] = {
        _id = "[Metal] Copper Bar",
        _displayName = "Copper Bars",
        _description = "Refined copper ore, used for crafting.\n \n <b>Produced in:</b> Smelter, Stamping Mill, Furnace, Grill",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 7.2,
        _tradingBuyValue = 12,
        _iconFilename = "Icon_Resource_CopperBar.png",
    },
    ["[Metal] Copper Ore"] = {
        _id = "[Metal] Copper Ore",
        _displayName = "Copper Ore",
        _description = "A soft and malleable metal.\n \n <b>Obtained in:</b> Mine",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_CopperOre.png",
    },
    ["[Metal] Crystalized Dew"] = {
        _id = "[Metal] Crystalized Dew",
        _displayName = "Crystalized Dew",
        _description = "Crystalized rain essence.\n \n <b>Produced in:</b> Forester's Hut, Alchemist's Hut, Brickyard, Beanery",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 7.2,
        _tradingBuyValue = 12,
        _iconFilename = "Icon_Resource_CrystalizedDew.png",
    },
    ["[Needs] Ale"] = {
        _id = "[Needs] Ale",
        _displayName = "Ale",
        _description = "Used for leisure at: Tavern, Monastery, Market, by Humans, Beavers. Villagers with a satisfied need for leisure have a higher chance of producing double yields.\n\n<b>Produced in:</b> Brewery, Distillery, Tinctury, Scribe",
        _category = "Consumable Items",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.95,
        _tradingBuyValue = 3.75,
        _iconFilename = "Icon_Resource_Ale.png",
    },
    ["[Needs] Boots"] = {
        _id = "[Needs] Boots",
        _displayName = "Boots",
        _description = "Sturdy and waterproof. Used as clothing by: Lizards, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Grants a movement speed bonus to villagers wearing them.\n\n<b>Produced in:</b> Cobbler, Leatherworker, Toolshop, Weaver",
        _category = "Consumable Items",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 0.9,
        _tradingBuyValue = 1.75,
        _iconFilename = "Icon_Resource_Boots 1.png",
    },
    ["[Needs] Coats"] = {
        _id = "[Needs] Coats",
        _displayName = "Coats",
        _description = "Reliable protection from the rain. Used as clothing by: Humans, Beavers, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Grants an additional Resolve bonus during the storm.\n\n<b>Produced in:</b> Clothier, Cooperage, Artisan, Druid's Hut",
        _category = "Consumable Items",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.1,
        _tradingBuyValue = 4.05,
        _iconFilename = "Icon_Resource_Coats.png",
    },
    ["[Needs] Incense"] = {
        _id = "[Needs] Incense",
        _displayName = "Incense",
        _description = "Used for religion at: Temple, Monastery, Tea Doctor, by Humans, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for religion have a higher chance of producing double yields.\n\n<b>Produced in:</b> Brick Oven, Teahouse, Distillery, Smokehouse",
        _category = "Consumable Items",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.1,
        _tradingBuyValue = 4.05,
        _iconFilename = "Icon_Resource_Incense.png",
    },
    ["[Needs] Scrolls"] = {
        _id = "[Needs] Scrolls",
        _displayName = "Scrolls",
        _description = "Used for education at: Temple, Holy Guild House, Guild House, Academy, by: Beavers, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for education have a higher chance of producing double yields.\n\n<b>Produced in:</b> Scribe, Artisan, Lumber Mill, Rain Mill",
        _category = "Consumable Items",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.44,
        _tradingBuyValue = 2.8,
        _iconFilename = "Icon_Resource_Scrolls.png",
    },
    ["[Needs] Tea"] = {
        _id = "[Needs] Tea",
        _displayName = "Tea",
        _description = "Used for treatment at: Market, Tea Doctor, Bath House, by: <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for treatment have a higher chance of producing double yields.\n\n<b>Produced in:</b> Teahouse, Apothecary, Alchemist's Hut, Druid's Hut",
        _category = "Consumable Items",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.8,
        _tradingBuyValue = 3.5,
        _iconFilename = "Icon_Resource_Tea.png",
    },
    ["[Needs] Training Gear"] = {
        _id = "[Needs] Training Gear",
        _displayName = "Training Gear",
        _description = "Used for brawling at: Clan Hall, Forum, Academy, by: Lizards, <color=#a9a9a9>Locked</color>, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for brawling have a higher chance of producing double yields.\n\n<b>Produced in:</b> Smelter, Tinkerer, Weaver, Leatherworker",
        _category = "Consumable Items",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.55,
        _tradingBuyValue = 4.9,
        _iconFilename = "Icon_Resource_TrainingGear.png",
    },
    ["[Needs] Wine"] = {
        _id = "[Needs] Wine",
        _displayName = "Wine",
        _description = "Used for luxury at: Tavern, Holy Guild House, Forum, Guild House, by: Beavers, <color=#a9a9a9>Locked</color>. Villagers with a satisfied need for luxury have a higher chance of producing double yields.\n\n<b>Produced in:</b> Cellar, Cannery, Alchemist's Hut, Tinctury",
        _category = "Consumable Items",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 1.5,
        _tradingBuyValue = 3,
        _iconFilename = "Icon_Resource_Wine.png",
    },
    ["[Other] Fertilizer"] = {
        _id = "[Other] Fertilizer",
        _displayName = "Fertilizer",
        _description = "An extremely valuable material that enables the creation of new patches of fertile soil. Can only be acquired with the help of the <b>Fluffbeak</b>.",
        _category = "Building Materials",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.4,
        _tradingBuyValue = 4,
        _iconFilename = "corn_b_01.png",
    },
    ["[Other] Fishing Bait"] = {
        _id = "[Other] Fishing Bait",
        _displayName = "Ground Bait",
        _description = "Bait made from Packs of Crops. Used in fishing huts to double fishing yields.",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.4,
        _tradingBuyValue = 4,
        _iconFilename = "Icon_Resource_GroundBait.png",
    },
    ["[Other] Fuel Rod"] = {
        _id = "[Other] Fuel Rod",
        _displayName = "Fuel Rods",
        _description = "A volatile fuel cell engineered to push Rain Engines to their absolute limit. Produced only in the <b>Field Engineering Station</b>.",
        _category = "Fuel & Exploration",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 192,
        _tradingBuyValue = 320,
        _iconFilename = "Icon_Resource_InfusedTools.png",
    },
    ["[Packs] Pack of Building Materials"] = {
        _id = "[Packs] Pack of Building Materials",
        _displayName = "Pack of Building Materials",
        _description = "Building materials packaged for delivery, used to fulfill orders, upgrade buildings, and trade.\n \n <b>Produced in:</b> Cobbler, Clothier, Makeshift Post",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 12,
        _tradingBuyValue = 20,
        _iconFilename = "Icon_Resource_BuildingMaterials.png",
    },
    ["[Packs] Pack of Crops"] = {
        _id = "[Packs] Pack of Crops",
        _displayName = "Pack of Crops",
        _description = "Crops packaged for delivery, used to fulfill orders and trade.\n \n <b>Produced in:</b> Granary, Brewery, Makeshift Post",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 12,
        _tradingBuyValue = 20,
        _iconFilename = "Icon_Resource_Crops.png",
    },
    ["[Packs] Pack of Luxury Goods"] = {
        _id = "[Packs] Pack of Luxury Goods",
        _displayName = "Pack of Luxury Goods",
        _description = "Goods highly sought after by traders. Can be used to fulfill orders, or sold for a large profit.\n \n <b>Produced in:</b> Carpenter, Pantry, Cooperage",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 18,
        _tradingBuyValue = 30,
        _iconFilename = "Icon_Resource_Luxury.png",
    },
    ["[Packs] Pack of Provisions"] = {
        _id = "[Packs] Pack of Provisions",
        _displayName = "Pack of Provisions",
        _description = "Provisions necessary for sending caravans into the wild. Used to fulfill orders, trade, and pay for trade routes.\n \n <b>Produced in:</b> Provisioner, Cellar, Makeshift Post",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 6,
        _tradingBuyValue = 10,
        _iconFilename = "Icon_Resource_Provisions.png",
    },
    ["[Packs] Pack of Trade Goods"] = {
        _id = "[Packs] Pack of Trade Goods",
        _displayName = "Pack of Trade Goods",
        _description = "Goods highly sought after by traders. Can be used to fulfill orders, or sold for a large profit.\n \n <b>Produced in:</b> Smithy, Scribe, Lumber Mill",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 18,
        _tradingBuyValue = 30,
        _iconFilename = "Icon_Resource_TradeGoods.png",
    },
    ["[Tools] Simple Tools"] = {
        _id = "[Tools] Simple Tools",
        _displayName = "Tools",
        _description = "Used primarily for exploration, opening caches, and completing difficult events.\n \n <b>Produced in:</b> Toolshop, Finesmith, Carpenter, Smithy, Tinkerer",
        _category = "Fuel & Exploration",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 16.65,
        _tradingBuyValue = 27.75,
        _iconFilename = "Icon_Resource_SimpleTools.png",
    },
    ["[Valuable] Amber"] = {
        _id = "[Valuable] Amber",
        _displayName = "Amber",
        _description = "Crystallized resin. The main currency of the kingdom.",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 12,
        _tradingBuyValue = 15,
        _iconFilename = "Icon_Resource_Amber.png",
    },
    ["[Valuable] Ancient Tablet"] = {
        _id = "[Valuable] Ancient Tablet",
        _displayName = "Ancient Tablet",
        _description = "Valuable sources of knowledge, highly sought after by traders and the Queen herself. They can be found in Dangerous (<sprite name=\"dangerous\">) or Forbidden Glades (<sprite name=\"forbidden\">).",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 96,
        _tradingBuyValue = 160,
        _iconFilename = "Icon_Resource_AncientTablet.png",
    },
    ["[Valuable] Thunderblight Shard"] = {
        _id = "[Valuable] Thunderblight Shard",
        _displayName = "Thunderblight Shard",
        _description = "A rare, lightning-infused crystal used in the creation of cornerstones. Obtained by mining in the Ashen Thicket.",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 96,
        _tradingBuyValue = 160,
        _iconFilename = "Icon_Resource_ThunderblightShard.png",
    },
    ["[Vessel] Barrels"] = {
        _id = "[Vessel] Barrels",
        _displayName = "Barrels",
        _description = "Used for crafting.\n \n <b>Produced in:</b> Cooperage, Provisioner, Artisan, Manufactory",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.4,
        _tradingBuyValue = 4,
        _iconFilename = "Icon_Resource_Barrels.png",
    },
    ["[Vessel] Pottery"] = {
        _id = "[Vessel] Pottery",
        _displayName = "Pottery",
        _description = "Used for crafting.\n \n <b>Produced in:</b> Bakery, Brickyard, Tinkerer, Smokehouse",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.1,
        _tradingBuyValue = 3.5,
        _iconFilename = "Icon_Resource_Pottery.png",
    },
    ["[Vessel] Waterskin"] = {
        _id = "[Vessel] Waterskin",
        _displayName = "Waterskins",
        _description = "Used for crafting.\n \n <b>Produced in:</b> Leatherworker, Supplier, Clothier, Teahouse",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 2.25,
        _tradingBuyValue = 3.75,
        _iconFilename = "Icon_Resource_Waterskins.png",
    },
    ["[Water] Clearance Water"] = {
        _id = "[Water] Clearance Water",
        _displayName = "Clearance Water",
        _description = "Highly concentrated yellow clearance rainwater. Used to power Rain Engines in crafting-oriented buildings.",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 0.75,
        _tradingBuyValue = 1.25,
        _iconFilename = "Icon_Resource_ClearanceWater.png",
    },
    ["[Water] Drizzle Water"] = {
        _id = "[Water] Drizzle Water",
        _displayName = "Drizzle Water",
        _description = "Highly concentrated green drizzle rainwater. Used to power Rain Engines in food-oriented buildings.",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 0.75,
        _tradingBuyValue = 1.25,
        _iconFilename = "Icon_Resource_DrizzleWater.png",
    },
    ["[Water] Storm Water"] = {
        _id = "[Water] Storm Water",
        _displayName = "Storm Water",
        _description = "Highly concentrated blue storm rainwater. Used to power Rain Engines in industry-oriented buildings.",
        _category = "Crafting Resources",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 0.75,
        _tradingBuyValue = 1.25,
        _iconFilename = "Icon_Resource_StormWater.png",
    },
    ["[WE] Fuel Core"] = {
        _id = "[WE] Fuel Core",
        _displayName = "Enriched Fuel",
        _description = "Charged rainwater sealed in a durable container. Essential for powering advanced machinery. Produced only in the <b>Field Engineering Station</b>.",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 96,
        _tradingBuyValue = 160,
        _iconFilename = "Icon_Resource_Sparkdew.png",
    },
    ["_Meta Artifacts"] = {
        _id = "_Meta Artifacts",
        _displayName = "Artifacts",
        _description = "The remnants of a long-forgotten world. Earned by completing world events, modifiers, seals, and daily expeditions. Can be used to purchase upgrades in the Smoldering City.",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 60,
        _tradingBuyValue = 90,
        _iconFilename = "Icon_MetaResource_Artifact.png",
    },
    ["_Meta Food Stockpiles"] = {
        _id = "_Meta Food Stockpiles",
        _displayName = "Food Stockpiles",
        _description = "A basic currency of the realm. Earned by completing settlements. Can be used to purchase upgrades in the Smoldering City.",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 30,
        _tradingBuyValue = 45,
        _iconFilename = "Icon_MetaResource_FoodStockpiles.png",
    },
    ["_Meta Machinery"] = {
        _id = "_Meta Machinery",
        _displayName = "Machinery",
        _description = "Rainpunk technology ripped from the past. Earned by completing world events, modifiers, seals, and daily expeditions. Can be used to purchase upgrades in the Smoldering City.",
        _category = "Trade Goods",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 60,
        _tradingBuyValue = 90,
        _iconFilename = "Icon_MetaResource_Machinery.png",
    },
    ["Blight Fuel"] = {
        _id = "Blight Fuel",
        _displayName = "Purging Fire",
        _description = "A unique resource used by Blight Fighters to burn down Blightrot Cysts. \n \n <b>Produced in:</b> Blight Post",
        _category = "Fuel & Exploration",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 3.75,
        _tradingBuyValue = 6.25,
        _iconFilename = "Icon_Resource_PurgingFire.png",
    },
    ["Hearth Parts"] = {
        _id = "Hearth Parts",
        _displayName = "Wildfire Essence",
        _description = "A sentient flame trapped in a bottle. This rare material is used to light the Holy Flame in Hearths. Can be acquired from orders, Glade Events, or traders.",
        _category = "Building Materials",
        _isEatable = false,
        _isBurnable = false,
        _burningTime = 0,
        _tradingSellValue = 30,
        _tradingBuyValue = 50,
        _iconFilename = "Icon_Resource_Wildfire.png",
    },
}