return {
    ["Bay"] = {
        _id = "Bay",
        _displayName = "Coastal Grove",
        _description = "These lands have been underwater for centuries, allowing a dense forest of algae to flourish. The surrounding seawater has almost completely cut off the area from the rest of the kingdom, leaving the nearby marshes almost untouched and full of the remains of ancient settlements.",
        _iconFilename = "Icon_Biome_Bay.png",
        _dlc = "Frogs",
        _soilGrade = "Average Amount",
        _deposits = {
            "Moor Node Reed Deposit - Small",
            "Universal Node Clay Deposit - Small",
            "Lake - Algae - Small",
            "Marsh Node Insect Nest - Small",
            "Universal Node Root Deposit - Small",
            "Universal Node Dewberries - Small",
            "Lake - Fish - Small",
            "Lake - Scales - Small",
            "Universal Node Dewberries - Big",
            "Universal Node Root Deposit - Big",
            "Marsh Node Insect Nest - Big",
            "Moor Node Reed Deposit - Big",
            "Universal Node Clay Deposit - Big",
            "Lake - Fish - Big",
            "Lake - Scales - Big",
            "Lake - Algae - Big"
        },
        _trees = {
            "Bay Tree 1",
            "Bay Tree 2"
        },
        _ores = {
            "Coal Ore"
        },
        _effects = {
            "[BIOME] AlgaeSacrifice",
            "[Biome] Replace Initial Glade - Port"
        },
        _townType = "Coastal Town",
        _tradeRouteResources = {
            "[Food Raw] Grain",
            "[Food Raw] Mushrooms",
            "[Food Processed] Biscuits",
            "[Food Processed] Pie",
            "[Food Processed] Pickled Goods",
            "[Mat Raw] Clay",
            "[Mat Raw] Resin",
            "[Crafting] Flour",
            "[Crafting] Dye",
            "[Metal] Copper Bar",
            "[Metal] Copper Ore",
            "[Needs] Ale",
            "[Needs] Tea",
            "[Needs] Incense",
            "[Needs] Training Gear",
            "[Vessel] Pottery",
            "[Packs] Pack of Trade Goods",
            "[Packs] Pack of Luxury Goods",
            "[Tools] Simple Tools",
            "[Vessel] Barrels",
            "[Packs] Pack of Building Materials",
            "[Food Processed] Porridge",
            "[Food Raw] Herbs",
            "[Mat Raw] Plant Fibre",
            "[Mat Processed] Bricks"
        },
    },
    ["Cave"] = {
        _id = "Cave",
        _displayName = "Rocky Ravine",
        _description = "Giant underground caverns siphon rainwater from this strange depression, uncovering lands rich in minerals and ore, yet barren of life. It’s a sought-after destination for both traders and smugglers.",
        _iconFilename = "Icon_Biom_Cave.png",
        _dlc = "Bats",
        _soilGrade = "Small Amount",
        _deposits = {
            "Universal Node Clay Deposit - Small",
            "Moor Node Reed Deposit - Small",
            "Lake - Algae - Small",
            "Universal Node Sea Marrow Deposit - Small",
            "Marsh Node Insect Nest - Small",
            "Lake - Fish - Small",
            "Moor Node Herbs - Small",
            "Moor Node Swamp Wheat - Small",
            "Marsh Node Insect Nest - Big",
            "Lake - Fish - Big",
            "Moor Node Herbs - Big",
            "Moor Node Swamp Wheat - Big",
            "Lake - Algae - Big",
            "Moor Node Reed Deposit - Big",
            "Universal Node Clay Deposit - Big",
            "Universal Node Sea Marrow Deposit - Big"
        },
        _trees = {
            "Cave Tree 2",
            "Cave Tree 1"
        },
        _ores = {
            "Copper Ore",
            "Coal Ore"
        },
        _effects = {
            "[BIOME] Faster Trade For Goods Sold",
            "[Biome] Cave - Black Market Blueprint",
            "[BIOME] Cave Initial Goods"
        },
        _townType = "Ravine Town",
        _tradeRouteResources = {
            "[Food Raw] Berries",
            "[Food Raw] Eggs",
            "[Food Raw] Meat",
            "[Food Raw] Mushrooms",
            "[Food Raw] Vegetables",
            "[Food Processed] Biscuits",
            "[Food Processed] Porridge",
            "[Food Processed] Paste",
            "[Food Processed] Pickled Goods",
            "[Food Processed] Skewers",
            "[Mat Raw] Leather",
            "[Mat Raw] Plant Fibre",
            "[Mat Raw] Resin",
            "[Mat Processed] Parts",
            "[Mat Processed] Planks",
            "[Crafting] Salt",
            "[Crafting] Sea Marrow",
            "[Needs] Ale",
            "[Needs] Coats",
            "[Needs] Scrolls",
            "[Needs] Training Gear",
            "[Vessel] Pottery",
            "[Packs] Pack of Building Materials",
            "[Packs] Pack of Trade Goods",
            "[Packs] Pack of Crops"
        },
    },
    ["Coral Forest"] = {
        _id = "Coral Forest",
        _displayName = "Coral Forest",
        _description = "The true source of the coral’s growth is unknown. Contrary to common belief, it doesn't usually appear in flooded regions. The unique influence of the coral mutates trees into distinctive strands that offer various resources.",
        _iconFilename = "Icon_Biome_CoralForest.png",
        _dlc = "None",
        _soilGrade = "Average Amount",
        _deposits = {
            "Moor Node Reed Deposit - Small",
            "Universal Node Stone Deposit - Small",
            "Wood Node Moss Broccoli - Small",
            "Marsh Node Big Reptile Nest - Small",
            "Marsh Node Insect Nest - Small",
            "Moor Node Herbs - Small",
            "Lake - Scales - Small",
            "Moor Node Herbs - Big",
            "Wood Node Moss Broccoli - Big",
            "Marsh Node Big Reptile Nest - Big",
            "Marsh Node Insect Nest - Big",
            "Universal Node Stone Deposit - Big",
            "Moor Node Reed Deposit - Big",
            "Lake - Scales - Big"
        },
        _trees = {
            "CoralForest_Plateleaf",
            "CoralForest_Musselsprout",
            "CoralForest_Crimsonreach"
        },
        _ores = {
            "Coal Ore",
            "Salt Ore"
        },
        _effects = {
            "[BIOME] Diverse Flora",
            "[BIOME] Inspiring Pressure Holder"
        },
        _townType = "Coral Enclave",
        _tradeRouteResources = {
            "[Food Raw] Berries",
            "[Food Raw] Grain",
            "[Food Raw] Mushrooms",
            "[Food Processed] Biscuits",
            "[Food Processed] Pie",
            "[Food Processed] Pickled Goods",
            "[Mat Raw] Clay",
            "[Mat Raw] Resin",
            "[Crafting] Flour",
            "[Crafting] Dye",
            "[Metal] Copper Bar",
            "[Metal] Copper Ore",
            "[Needs] Ale",
            "[Needs] Tea",
            "[Needs] Training Gear",
            "[Vessel] Pottery",
            "[Packs] Pack of Crops",
            "[Packs] Pack of Luxury Goods",
            "[Tools] Simple Tools",
            "[Vessel] Barrels",
            "[Food Processed] Porridge",
            "[Food Raw] Fish",
            "[Food Raw] Roots",
            "[Mat Raw] Algae",
            "[Packs] Pack of Trade Goods"
        },
    },
    ["Cursed Royal Woodlands"] = {
        _id = "Cursed Royal Woodlands",
        _displayName = "Cursed Royal Woodlands",
        _description = "A cursed area of the Royal Woodlands that is haunted by the lost souls of warriors fallen in the Great Civil War. The storm here is especially dangerous, and the forest more hostile than anywhere else. The Queen will handsomely reward any viceroy brave enough to settle this part of the world.",
        _iconFilename = "Icon_Biome_Cursed.png",
        _dlc = "None",
        _soilGrade = "Average Amount",
        _deposits = {
            "Universal Node Clay Deposit - Small",
            "Wood Node Flax - Small",
            "Universal Node Mushroom Deposit - Small",
            "Wood Node Moss Broccoli - Small",
            "Marsh Node Insect Nest - Small",
            "Lake - Fish - Small",
            "Moor Node Herbs - Small",
            "Moor Node Swamp Wheat - Small",
            "Universal Node Sea Marrow Deposit - Small",
            "Universal Node Leather - Small",
            "Moor Node Herbs - Big",
            "Universal Node Mushroom Deposit - Big",
            "Moor Node Swamp Wheat - Big",
            "Wood Node Moss Broccoli - Big",
            "Marsh Node Insect Nest - Big",
            "Wood Node Flax - Big",
            "Universal Node Clay Deposit - Big",
            "Universal Node Sea Marrow Deposit - Big",
            "Lake - Fish - Big",
            "Universal Node Leather - Big"
        },
        _trees = {
            "Cursed Tree"
        },
        _ores = {
            "Copper Ore",
            "Salt Ore"
        },
        _effects = {
            "[Biome] Ghosts in Cursed Woodlands",
            "[BIOME] Cursed Glades"
        },
        _townType = "Cursed Village",
        _tradeRouteResources = {
            "[Food Raw] Berries",
            "[Food Raw] Eggs",
            "[Food Raw] Meat",
            "[Food Raw] Roots",
            "[Food Processed] Jerky",
            "[Food Processed] Skewers",
            "[Mat Raw] Reeds",
            "[Mat Raw] Stone",
            "[Mat Processed] Planks",
            "[Crafting] Oil",
            "[Crafting] Coal",
            "[Needs] Tea",
            "[Needs] Incense",
            "[Needs] Scrolls",
            "[Vessel] Waterskin",
            "[Valuable] Ancient Tablet",
            "[Packs] Pack of Crops",
            "[Packs] Pack of Trade Goods",
            "[Packs] Pack of Building Materials",
            "[Food Processed] Porridge",
            "[Food Processed] Paste",
            "[Mat Raw] Algae",
            "[Needs] Boots",
            "[Crafting] Salt",
            "[Mat Raw] Scales"
        },
    },
    ["Moorlands"] = {
        _id = "Moorlands",
        _displayName = "Scarlet Orchard",
        _description = "A beautiful yet dangerous land that is colored a strange shade of crimson. It's called the Herb Garden of the Kingdom due to its abundance of herbs, berries, and roots.",
        _iconFilename = "Icon_Biome_ScarletOrchard.png",
        _dlc = "None",
        _soilGrade = "Average Amount",
        _deposits = {
            "Moor Node Reed Deposit - Small",
            "Universal Node Stone Deposit - Small",
            "Universal Node Dewberries - Small",
            "Universal Node Root Deposit - Small",
            "Universal Node Stormbird Nest - Small",
            "Lake - Fish - Small",
            "Moor Node Herbs - Small",
            "Moor Node Swamp Wheat - Small",
            "Universal Node Sea Marrow Deposit - Small",
            "Universal Node Leather - Small",
            "Moor Node Herbs - Big",
            "Universal Node Dewberries - Big",
            "Moor Node Swamp Wheat - Big",
            "Universal Node Root Deposit - Big",
            "Universal Node Stormbird Nest - Big",
            "Moor Node Reed Deposit - Big",
            "Universal Node Stone Deposit - Big",
            "Universal Node Sea Marrow Deposit - Big",
            "Lake - Fish - Big",
            "Universal Node Leather - Big"
        },
        _trees = {
            "Moorlands Tree",
            "Moorlands Tree 2"
        },
        _ores = {
            "Copper Ore",
            "Salt Ore"
        },
        _effects = {
            "[Biome] Moorlands - Archaeologist Blueprint",
            "[Biome] Moorlands - glades"
        },
        _townType = "Orchard Town",
        _tradeRouteResources = {
            "[Food Raw] Insects",
            "[Food Raw] Meat",
            "[Food Raw] Mushrooms",
            "[Food Raw] Vegetables",
            "[Food Processed] Jerky",
            "[Food Processed] Skewers",
            "[Mat Raw] Clay",
            "[Mat Processed] Bricks",
            "[Mat Processed] Fabric",
            "[Mat Processed] Parts",
            "[Crafting] Oil",
            "[Crafting] Coal",
            "[Metal] Crystalized Dew",
            "[Needs] Coats",
            "[Needs] Training Gear",
            "[Vessel] Pottery",
            "[Vessel] Waterskin",
            "[Packs] Pack of Building Materials",
            "[Packs] Pack of Trade Goods",
            "[Mat Raw] Leather",
            "[Packs] Pack of Crops",
            "[Mat Raw] Scales",
            "[Mat Raw] Algae",
            "[Crafting] Salt"
        },
    },
    ["Poro Biome"] = {
        _id = "Poro Biome",
        _displayName = "Bamboo Flats",
        _description = "A lush, verdant expanse covered by an endless sea of bamboo trees. It is home to the magnificent Fluffbeaks - a species of gentle giants who love nothing more than to munch on the sweet stems and leaves of Tearsap Bamboo.",
        _iconFilename = "Icon_Biom_Poro.png",
        _dlc = "Bats",
        _soilGrade = "None",
        _deposits = {
            "Universal Node Stone Deposit - Small",
            "Wood Node Flax - Small",
            "Universal Node Dewberries - Small",
            "Wood Node Moss Broccoli - Small",
            "Marsh Node Big Reptile Nest - Small",
            "Moor Node Swamp Wheat - Small",
            "Moor Node Herbs - Small",
            "Lake - Scales - Small",
            "Universal Node Leather - Small",
            "Universal Node Dewberries - Big",
            "Wood Node Moss Broccoli - Big",
            "Marsh Node Big Reptile Nest - Big",
            "Moor Node Swamp Wheat - Big",
            "Moor Node Herbs - Big",
            "Wood Node Flax - Big",
            "Universal Node Stone Deposit - Big",
            "Lake - Scales - Big",
            "Universal Node Leather - Big"
        },
        _trees = {
            "Poro Biome Tree 1",
            "Poro Biome Tree 2"
        },
        _ores = {
            "Salt Ore"
        },
        _effects = {
            "[Biome] Poro Biome - Grass Spawner Blueprint",
            "[Biome] Replace Initial Glade - Poro",
            "[Biome] Farms Extra Production For Fertilizer"
        },
        _townType = "Bamboo Refuge",
        _tradeRouteResources = {
            "[Food Raw] Eggs",
            "[Food Raw] Fish",
            "[Food Raw] Insects",
            "[Food Raw] Mushrooms",
            "[Food Raw] Roots",
            "[Mat Raw] Clay",
            "[Mat Raw] Algae",
            "[Mat Raw] Reeds",
            "[Mat Processed] Bricks",
            "[Mat Processed] Fabric",
            "[Mat Processed] Parts",
            "[Mat Processed] Planks",
            "[Crafting] Coal",
            "[Metal] Copper Ore",
            "[Crafting] Sea Marrow",
            "[Metal] Copper Bar",
            "[Metal] Crystalized Dew",
            "[Needs] Coats",
            "[Needs] Wine",
            "[Tools] Simple Tools",
            "[Vessel] Barrels",
            "[Packs] Pack of Crops",
            "[Packs] Pack of Trade Goods",
            "[Packs] Pack of Luxury Goods"
        },
    },
    ["Royal Woodlands"] = {
        _id = "Royal Woodlands",
        _displayName = "Royal Woodlands",
        _description = "The Queen's forests were once part of the Smoldering City, but the Blightstorm reclaimed this land. The Royal Woodlands are rich in roots, moss broccoli, mushrooms, and flax, with a decent amount of dewberries and clay. The ground is fertile and soft, which makes it perfect for farming.",
        _iconFilename = "Icon_Biome_Royal Woodlands.png",
        _dlc = "None",
        _soilGrade = "Average Amount",
        _deposits = {
            "Universal Node Clay Deposit - Small",
            "Wood Node Flax - Small",
            "Universal Node Dewberries - Small",
            "Universal Node Mushroom Deposit - Small",
            "Universal Node Root Deposit - Small",
            "Wood Node Moss Broccoli - Small",
            "Wood Node Snail Broodmother - Small",
            "Universal Node Stormbird Nest - Small",
            "Universal Node Sea Marrow Deposit - Small",
            "Lake - Scales - Small",
            "Universal Node Dewberries - Big",
            "Universal Node Mushroom Deposit - Big",
            "Universal Node Root Deposit - Big",
            "Wood Node Moss Broccoli - Big",
            "Wood Node Snail Broodmother - Big",
            "Universal Node Stormbird Nest - Big",
            "Wood Node Flax - Big",
            "Universal Node Clay Deposit - Big",
            "Universal Node Sea Marrow Deposit - Big",
            "Lake - Scales - Big"
        },
        _trees = {
            "Woodlands Tree"
        },
        _ores = {},
        _effects = {
            "[Biome] Wood in Woodlands"
        },
        _townType = "Woodland Town",
        _tradeRouteResources = {
            "[Food Raw] Herbs",
            "[Food Raw] Insects",
            "[Mat Raw] Reeds",
            "[Mat Raw] Stone",
            "[Mat Processed] Bricks",
            "[Mat Processed] Fabric",
            "[Mat Processed] Parts",
            "[Crafting] Oil",
            "[Crafting] Coal",
            "[Metal] Copper Bar",
            "[Metal] Copper Ore",
            "[Needs] Training Gear",
            "[Needs] Wine",
            "[Tools] Simple Tools",
            "[Vessel] Barrels",
            "[Packs] Pack of Building Materials",
            "[Packs] Pack of Trade Goods",
            "[Metal] Crystalized Dew",
            "[Packs] Pack of Luxury Goods",
            "[Mat Raw] Leather",
            "[Needs] Boots",
            "[Mat Raw] Algae",
            "[Food Raw] Fish",
            "[Crafting] Salt",
            "[Food Raw] Grain"
        },
    },
    ["Sealed Biome"] = {
        _id = "Sealed Biome",
        _displayName = "Sealed Forest",
        _description = "Somewhere in this thick and dark forest, an ancient seal is hidden. Even the Ancients, in all their might and glory, couldn't defeat the creatures slumbering below - so they just imprisoned them. Over millennia, their sinister power gradually seeped to the surface, infecting the fauna and flora of this region. Viceroys don't embark here to establish settlements or gain reputation - their main goal is simply to find and close the seal.",
        _iconFilename = "Icon_Biome_Sealed Forest.png",
        _dlc = "None",
        _soilGrade = "Average Amount",
        _deposits = {
            "Universal Node Clay Deposit - Small",
            "Moor Node Reed Deposit - Small",
            "Lake - Algae - Small",
            "Universal Node Dewberries - Small",
            "Universal Node Mushroom Deposit - Small",
            "Universal Node Root Deposit - Small",
            "Wood Node Snail Broodmother - Small",
            "Marsh Node Insect Nest - Small",
            "Universal Node Sea Marrow Deposit - Small",
            "Lake - Scales - Small",
            "Universal Node Dewberries - Big",
            "Universal Node Mushroom Deposit - Big",
            "Universal Node Root Deposit - Big",
            "Wood Node Snail Broodmother - Big",
            "Marsh Node Insect Nest - Big",
            "Moor Node Reed Deposit - Big",
            "Universal Node Clay Deposit - Big",
            "Universal Node Sea Marrow Deposit - Big",
            "Lake - Scales - Big",
            "Lake - Algae - Big"
        },
        _trees = {
            "Last Biome 1",
            "Last Biome 2",
            "Last Biome 3",
            "Last Biome 4"
        },
        _ores = {
            "Copper Ore",
            "Salt Ore"
        },
        _effects = {
            "[BIOME] Sealed Biome",
            "[BIOME] Big Trees",
            "[BIOME] Tree Hostility",
            "Extra Glade - Seal"
        },
        _townType = "Sealed Hamlet",
        _tradeRouteResources = {
            "[Food Raw] Herbs",
            "[Food Raw] Insects",
            "[Mat Raw] Reeds",
            "[Mat Raw] Stone",
            "[Mat Processed] Bricks",
            "[Mat Processed] Fabric",
            "[Mat Processed] Parts",
            "[Crafting] Oil",
            "[Crafting] Coal",
            "[Metal] Copper Bar",
            "[Metal] Copper Ore",
            "[Needs] Training Gear",
            "[Needs] Wine",
            "[Tools] Simple Tools",
            "[Vessel] Barrels",
            "[Packs] Pack of Building Materials",
            "[Packs] Pack of Trade Goods",
            "[Metal] Crystalized Dew"
        },
    },
    ["The Marshlands"] = {
        _id = "The Marshlands",
        _displayName = "Marshlands",
        _description = "A harsh and cold land that has been claimed by many different, and extremely resilient species of fungi. The ground here is extremely hard and rocky, making it difficult to farm. This region is most famous for the giant organisms that can be found in its forests.",
        _iconFilename = "Icon_Biome_Marshlands.png",
        _dlc = "None",
        _soilGrade = "Small Amount",
        _deposits = {
            "Marsh Node Stone Deposit - Small",
            "Lake - Algae - Small",
            "Marsh Node Mushroom Deposit - Small",
            "Marsh Node Big Reptile Nest - Small",
            "Marsh Node Small Reptile Nest - Small",
            "Moor Node Swamp Wheat - Small",
            "Universal Node Leather - Small",
            "Marsh Node Mushroom Deposit - Big",
            "Moor Node Swamp Wheat - Big",
            "Marsh Node Big Reptile Nest - Big",
            "Marsh Node Small Reptile Nest - Big",
            "Marsh Node Stone Deposit - Big",
            "Lake - Algae - Big",
            "Universal Node Leather - Big",
            "Marsh Infinite Node Grain",
            "Marsh Infinite Node Meat",
            "Marsh Infinite Node Mushrooms"
        },
        _trees = {
            "Mushroom Tree Bugs",
            "Mushroom Tree Classic"
        },
        _ores = {
            "Coal Ore",
            "Copper Ore"
        },
        _effects = {
            "[BIOME] Marshlands Camps Speed",
            "[BIOME] Giant Organisms"
        },
        _townType = "Marshland Settlement",
        _tradeRouteResources = {
            "[Food Raw] Berries",
            "[Food Raw] Herbs",
            "[Food Raw] Vegetables",
            "[Food Processed] Biscuits",
            "[Food Processed] Pickled Goods",
            "[Food Processed] Pie",
            "[Mat Raw] Clay",
            "[Mat Raw] Plant Fibre",
            "[Mat Raw] Reeds",
            "[Mat Raw] Resin",
            "[Crafting] Flour",
            "[Crafting] Dye",
            "[Needs] Ale",
            "[Needs] Tea",
            "[Needs] Incense",
            "[Needs] Scrolls",
            "[Needs] Wine",
            "[Packs] Pack of Crops",
            "[Packs] Pack of Luxury Goods",
            "[Food Raw] Insects",
            "[Food Raw] Roots",
            "[Crafting] Sea Marrow",
            "[Packs] Pack of Trade Goods",
            "[Mat Raw] Scales",
            "[Food Raw] Fish"
        },
    },
    ["Wasteland"] = {
        _id = "Wasteland",
        _displayName = "Ashen Thicket",
        _description = "Once a thriving forest of giant ashen trees, this land has been ravaged by relentless industrial exploitation and heavy mining, all driven by the lure of Thunderblight Shards - magically charged amber crystals used to craft cornerstones.",
        _iconFilename = "Icon_Biom_Ashen.png",
        _dlc = "Frogs",
        _soilGrade = "Average Amount",
        _deposits = {
            "Universal Node Clay Deposit - Small",
            "Wood Node Flax - Small",
            "Lake - Algae - Small",
            "Wood Node Moss Broccoli - Small",
            "Marsh Node Small Reptile Nest - Small",
            "Lake - Fish - Small",
            "Universal Node Root Deposit - Small",
            "Universal Node Mushroom Deposit - Small",
            "Universal Node Leather - Small",
            "Universal Node Root Deposit - Big",
            "Wood Node Moss Broccoli - Big",
            "Marsh Node Small Reptile Nest - Big",
            "Lake - Fish - Big",
            "Lake - Algae - Big",
            "Wood Node Flax - Big",
            "Universal Node Leather - Big",
            "Universal Node Clay Deposit - Big",
            "Universal Node Mushroom Deposit - Big"
        },
        _trees = {
            "Wasteland Tree 1",
            "Wasteland Tree 2"
        },
        _ores = {
            "Copper Ore",
            "Coal Ore",
            "Salt Ore"
        },
        _effects = {
            "[BIOME] Shards for Relics 1",
            "[Biome] Replace Initial Glade - Forge",
            "[BIOME] Carts For Using Ore"
        },
        _townType = "Ashen Hollow",
        _tradeRouteResources = {
            "[Food Raw] Grain",
            "[Food Raw] Herbs",
            "[Food Raw] Insects",
            "[Food Raw] Meat",
            "[Food Processed] Jerky",
            "[Food Processed] Paste",
            "[Food Processed] Pie",
            "[Mat Raw] Scales",
            "[Mat Raw] Reeds",
            "[Mat Raw] Stone",
            "[Mat Processed] Fabric",
            "[Crafting] Flour",
            "[Crafting] Dye",
            "[Crafting] Sea Marrow",
            "[Metal] Crystalized Dew",
            "[Needs] Boots",
            "[Needs] Coats",
            "[Needs] Incense",
            "[Needs] Wine",
            "[Vessel] Waterskin",
            "[Packs] Pack of Building Materials",
            "[Packs] Pack of Luxury Goods",
            "[Packs] Pack of Trade Goods",
            "[Crafting] Oil"
        },
    },
}